data:
  img_size: [224, 224]
  batch_size: 4 # 8
  path: "/home/anhkhoa/Medical-Image-Classification/Dataset/Data"

adam:
  lr: 0.0001 # 1e-4

model:
  d_model: 768
  encoder_layers: 6
  patch_size: 16
  num_classes: 4
  epochs: 10
  save_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/miafex"
  


svm:
  model_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/miafex_svm"
  C: 10.0
  kernel: 'rbf'
  degree: 2

lr:
  model_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/miafex_lr"
  solver: 'lbfgs'
  C: 1.0
  max_iter: 1000
  random_state: 42


rf:
  model_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/miafex_rf"
  n_estimators: 100
  criterion: 'gini'
  random_state: 42

xgb:
  model_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/miafex_xgb"
  n_estimators: 100
  max_depth: 6
  lr: 0.1
  random_state: 42
  num_classes: 4

results:
  save_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/miafex_infer.json"