data:
  img_size: [224, 224]
  batch_size: 4 # 8
  path: "/home/anhkhoa/Medical-Image-Classification/Dataset/Data"

adam:
  lr: 0.0001 # 1e-4

model:
  num_classes: 4
  epochs: 10
  save_path: "/home/anhkhoa/Medical-Image-Classification/src/save_path/resnet"