model:
  name: RFClassifier
  params:
    n_estimators: [100, 200]
    max_depth: [10, null]

feature_extractor:
  name: GLCMFeatureExtractor
  params:
    distances: [[1]]
    angles: [[0, 0.785, 1.571, 2.356]]
    properties: [["contrast", "dissimilarity", "homogeneity", "energy"]]

dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

output:
  dir: "results"
