dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

feature_extractor:
  name: "LBPFeatureExtractor"
  params:
    radius: [1, 2, 3]
    n_points: [8, 12]
    method: ["uniform", "default"]

model:
  name: "LRClassifier"
  params:
    max_iter: [100, 300, 500, 1000]

output:
  dir: "results/gridsearch"
