model:
  name: "RFClassifier"
  params:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, 30, null]

feature_extractor:
  name: "LBPFeatureExtractor"
  params:
    radius: [1, 2, 3]
    n_points: [8, 12]
    method: ["uniform", "default"]

dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

output:
  dir: "results/gridsearch"
