model:
  name: "RFClassifier"
  params:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, 30, null]
dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

feature_extractor:
  name: "GLCMFeatureExtractor"

output:
  dir: "results/gridsearch"
