dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

feature_extractor:
  name: "GaborFeatureExtractor"
  params:
    kernel_size: [7, 14, 21]
    sigma: [1, 2, 3]

model:
  name: "LRClassifier"
  params:
    max_iter: [100, 300, 500, 1000]

output:
  dir: "results/gridsearch"
