model:
  name: SVMClassifier
  params:
    C: [1, 10]
    kernel: ["rbf", "linear"]
    degree: [1, 2, 3]

feature_extractor:
  name: GLCMFeatureExtractor
  params:
    distances: [[1]]
    angles: [[0, np.pi/4, np.pi/2, 3*np.pi/4]]
    properties: [["contrast", "dissimilarity", "homogeneity", "energy"]]

dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

output:
  dir: "results"
