dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

feature_extractor:
  name: "LBPFeatureExtractor"

model:
  name: "KNNClassifier"
  params:
    n_neighbors: [3, 5, 7, 9]
    weights: ["uniform", "distance"]
    metric: ["euclidean", "manhattan"]

output:
  dir: "results/gridsearch"
