dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

feature_extractor:
  name: "HOGFeatureExtractor"
  params:
    orientations: [6, 9, 12]
    pixels_per_cell: [4, 8, 16]
    cells_per_block: [1, 2, 3]

model:
  name: "LRClassifier"
  params:
    max_iter: [100, 300, 500, 1000]

output:
  dir: "results/gridsearch"
