model:
  name: RFClassifier
  params:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, None]
    min_samples_split: [5, 10]
    min_samples_leaf: [2, 4]

feature_extractor:
  name: HOGFeatureExtractor
  params:
    orientations: [8, 9, 10]
    pixels_per_cell: [[8, 8], [16, 16]]
    cells_per_block: [[2, 2], [3, 3]]

dataset:
  data_dir: "Dataset/Data"
  image_size: [224, 224]
  color_mode: "grayscale"

output:
  dir: "results"
